/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.DDRecibo;
import Logica.LDRecibo;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import Datos.DRecibo;
import Logica.LRecibo;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Tecnico
 */
public class frmDetaRecibo extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmDetaRecibo
     */
    public frmDetaRecibo() {
        initComponents();
        
        BuscarDRecibo();
     
    }
    
    public void BuscarDRecibo() {
        
        DefaultTableModel miModelo;
        LDRecibo lf = new LDRecibo();
        miModelo = lf.MostrarRecibos();
        tblRecibo.setModel(miModelo);
        
    }
    
    public void Buscar(int txt) {
        DefaultTableModel miModelo;
        LRecibo lf = new LRecibo();
        DRecibo ddr = new DRecibo();
        ddr.setIdRecibo(txt);
        miModelo = lf.BuscarRecibos(ddr);
        tblRecibo.setModel(miModelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblRecibo = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        txtReporte = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de Recibo"));

        tblRecibo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FECHA", "PERSONA/ENTREGA", "PERSONA/RECIBE"
            }
        ));
        tblRecibo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblReciboMousePressed(evt);
            }
        });
        jScrollPane8.setViewportView(tblRecibo);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        txtReporte.setText("Reporte de Recibo");
        txtReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtReporte)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtReporte)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblReciboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReciboMousePressed
        // TODO add your handling code here:

        if (evt.getClickCount() == 2) {
            
            String id = tblRecibo.getValueAt(tblRecibo.getSelectedRow(), 0).toString();
            String Fecha = tblRecibo.getValueAt(tblRecibo.getSelectedRow(), 1).toString();
            String PEntrega = tblRecibo.getValueAt(tblRecibo.getSelectedRow(), 2).toString();
            String PRecibe = tblRecibo.getValueAt(tblRecibo.getSelectedRow(), 3).toString();
            
            frmReciboDet mi = new frmReciboDet(new JFrame(), true);
            mi.setDatos(id, Fecha, PEntrega, PRecibe);
            mi.setLocationRelativeTo(null);
            mi.setVisible(true);
            
        }
    }//GEN-LAST:event_tblReciboMousePressed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        // TODO add your handling code here:
       
        if (txtBuscar.getText().equals("")) {
          
             BuscarDRecibo();
             
        } else {
             
            Buscar(Integer.parseInt(txtBuscar.getText()));
            int aumenta = evt.getKeyCode();
            aumenta += aumenta;
            if (aumenta <= 20) {
                
                txtBuscar.setText("");
                
            }
            
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void txtReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReporteActionPerformed
        // TODO add your handling code here:
        
        JFileChooser seleccionar = new JFileChooser();

        int opcion = seleccionar.showSaveDialog(null);

        if (opcion == JFileChooser.APPROVE_OPTION) {

            String ruta = seleccionar.getSelectedFile().getAbsolutePath();

            String nombrereporte = ruta + ".xlsx";

            String nombrehoja = "Recibos";

            XSSFWorkbook libroInventario = new XSSFWorkbook();
            XSSFSheet hojaInventario = libroInventario.createSheet(nombrehoja);

            String[] titulos = new String[]{"ID", "FECHA", "PERSONA/ENTREGA", "PERSONA/RECIBE"};

            Font fontcabecera = libroInventario.createFont();
            fontcabecera.setBold(true);
            
            CellStyle cabecera=libroInventario.createCellStyle();
            
            cabecera.setBorderBottom(BorderStyle.THIN);
            cabecera.setBorderLeft(BorderStyle.THIN);
            cabecera.setBorderRight(BorderStyle.THIN);
            cabecera.setBorderTop(BorderStyle.THIN);
            cabecera.setFillForegroundColor(IndexedColors.BLUE.getIndex());
            cabecera.setFillPattern(FillPatternType.SOLID_FOREGROUND);
            cabecera.setFont(fontcabecera);
         
            CellStyle contenido2=libroInventario.createCellStyle();
            contenido2.setBorderBottom(BorderStyle.THIN);
            contenido2.setBorderLeft(BorderStyle.THIN);
            contenido2.setBorderRight(BorderStyle.THIN);
            contenido2.setBorderTop(BorderStyle.THIN);
            
            XSSFRow titulo = hojaInventario.createRow(0);

            for (int i = 0; i < titulos.length; i++) {
                XSSFCell celda = titulo.createCell(i);
                celda.setCellValue(titulos[i]);
                celda.setCellStyle(cabecera);
            }
            int filacontenido = 1;

            for (int i = 0; i < tblRecibo.getRowCount(); i++) { //getRowCount devuelve el numero de filas

                XSSFRow contenido = hojaInventario.createRow(filacontenido);
                filacontenido++;
                for (int j = 0; j < tblRecibo.getColumnCount(); j++) {// getColumnCount devuelve el numero de columnas

                    XSSFCell celda = contenido.createCell(j);
                    celda.setCellValue(tblRecibo.getValueAt(i, j).toString());
                    
                    celda.setCellStyle(contenido2);

                }
            }

            //            for (int i = 0; i < tblInvetario.getRowCount(); i++) {
                //                hojaInventario.autoSizeColumn(i);
                //
                //            }

            hojaInventario.autoSizeColumn(0);
            hojaInventario.autoSizeColumn(1);
            hojaInventario.autoSizeColumn(2);
            hojaInventario.autoSizeColumn(3);
        

            try (OutputStream archivo = new FileOutputStream(nombrereporte)) {

                libroInventario.write(archivo);

                JOptionPane.showMessageDialog(null, "Reporte se Descargo correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);

            } catch (IOException e) {

                JOptionPane.showMessageDialog(null, "No se pudo Descargar", "Informacion", JOptionPane.ERROR_MESSAGE);

                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_txtReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable tblRecibo;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JButton txtReporte;
    // End of variables declaration//GEN-END:variables
}
