/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.DFactura;
import Datos.DLineas;
import Logica.LFactura;
import java.awt.Event;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tecnico
 */
public class frmFacturas extends javax.swing.JInternalFrame {

   
    
    private DefaultTableModel miModelo;
    
    private int id;
    
    /**
     * Creates new form frmFacturas
     */
    public frmFacturas() {
        initComponents();
        
        
        txtid.setEnabled(false);
// ----------------- Codigo de tabla para dar tamaño y ejecucion ---------------
        miModelo=(DefaultTableModel) tblFactura.getModel();
        
        tblFactura.getColumn("Codigo").setWidth(18);
        tblFactura.getColumn("Codigo").setPreferredWidth(18);
        
        tblFactura.getColumn("Descriccion").setWidth(190);
        tblFactura.getColumn("Descriccion").setPreferredWidth(190);
        
        tblFactura.getColumn("Cantidad").setWidth(35);
        tblFactura.getColumn("Cantidad").setPreferredWidth(35);
        
        tblFactura.getColumn("U/Medida").setWidth(40);
        tblFactura.getColumn("U/Medida").setPreferredWidth(40);
        
        tblFactura.getColumn("P/Unitario").setWidth(40);
        tblFactura.getColumn("P/Unitario").setPreferredWidth(40);
        
        tblFactura.getColumn("Total").setWidth(30);
        tblFactura.getColumn("Total").setPreferredWidth(30);
        
// ----------------- Codigo de tabla para dar tamaño y ejecucion ---------------
        
     }
    public void idfact(int id) {
        
        this.id=id;
    
    }

    public static void setlineas(String id, String Lineas){
        
        idLineas.setText(id);
        txtLinea.setText(Lineas);
        
    }
     public static void setProveedor(String id, String Proveedor){
        
        idProveedores.setText(id);
        txtProveedor.setText(Proveedor);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtLinea = new javax.swing.JTextField();
        txtProveedor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFactura = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnLinea = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        txtFecha = new com.toedter.calendar.JDateChooser();
        idLineas = new javax.swing.JLabel();
        idProveedores = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Facturas");

        jLabel1.setText("ID");

        jLabel2.setText("Linea");

        jLabel3.setText("Proveedor");

        jLabel4.setText("Fecha");

        tblFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descriccion", "Cantidad", "U/Medida", "P/Unitario", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblFactura);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnLinea.setText("...");
        btnLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineaActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        btnProveedor.setText("...");
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });

        idLineas.setText("jLabel5");

        idProveedores.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLinea)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProveedor)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(idProveedores)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(idLineas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(btnLinea)
                        .addComponent(idLineas)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProveedor)
                    .addComponent(idProveedores))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        int fila=tblFactura.getRowCount();

        if(fila >= 10){
            miModelo.addRow(new Object[]{fila,"","","","",""});
        }else{
            miModelo.addRow(new Object[]{"0"+fila,"","","","",""});
        
        }
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineaActionPerformed
        // TODO add your handling code here:
        
        frmBuscarLinea mi=new frmBuscarLinea(new JFrame(),true);
        mi.setLocationRelativeTo(null);
        mi.setVisible(true);
        
       /* DLineas dl=new DLineas();
        txtLinea.setText(dl.getLineas());*/
    }//GEN-LAST:event_btnLineaActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        // TODO add your handling code here:
        
        frmBuscarProveedor mi=new frmBuscarProveedor(new JFrame(),true);
        mi.setLocationRelativeTo(null);
        mi.setVisible(true);
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String msj;
        if(txtLinea.getText().equals("") || txtProveedor.getText().equals("") || txtFecha.getDate().equals("")){
            JOptionPane.showMessageDialog(null, "Debe Completar los Formularios deben de estar llenos", "Informacion", JOptionPane.QUESTION_MESSAGE);
           txtLinea.requestFocusInWindow();
           return;
        }
            if(txtid.getText().equals("")){
            DFactura df=new DFactura();
            LFactura lf=new LFactura();
       
           df.setIdLinea(Integer.parseInt(idLineas.getText()));
           df.setIdProveedor(Integer.parseInt(idProveedores.getText()));
           
           Calendar cl;
           
           cl=txtFecha.getCalendar();
           int dd,mm,aa;
           
           dd=cl.get(Calendar.DAY_OF_WEEK)-1900;
           mm=cl.get(Calendar.MONTH);
           aa=cl.get(Calendar.YEAR);
           
           df.setFecha(new Date(aa,mm,dd));
           //df.setIdLinea(id);
           msj=lf.InsartarFc(df);
           
           if(msj=="si"){
               JOptionPane.showMessageDialog(null, "El Item Se guardo exitosamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
           }else{
               JOptionPane.showMessageDialog(null, "Ah Ocurrido un Error", "Informacion", JOptionPane.ERROR_MESSAGE);
           }
       }
//        Este Else se usa para Editar la informacion y esta en el mismo Boton Guardar-----------------------------------------*
       /* else{
            
           
           df.setIdLinea(Integer.parseInt(txtLinea.getText()));
           df.setIdProveedor(Integer.parseInt(txtProveedor.getText()));
           df.setIdLinea(id);
           
            msj=lf.EditarLn(df);
            
             if(msj=="si"){
               JOptionPane.showMessageDialog(null, "El Item Se Actualizo ", "Informacion", JOptionPane.INFORMATION_MESSAGE);
           }else{
               JOptionPane.showMessageDialog(null, "Ah Ocurrido un Error al actualizar", "Informacion", JOptionPane.ERROR_MESSAGE);
           }
            }*/
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLinea;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnProveedor;
    private static javax.swing.JLabel idLineas;
    private static javax.swing.JLabel idProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFactura;
    private com.toedter.calendar.JDateChooser txtFecha;
    private static javax.swing.JTextField txtLinea;
    private static javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables

    
}
