/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Tecnico
 */
public class frmRespaldarRestaura extends javax.swing.JInternalFrame {

    private static final String pass = "olivar2021";
    private static final String user = "root2";
    private static final String db="dbalmacen";
    /**
     * Creates new form frmRespaldarRestaura
     */
    public frmRespaldarRestaura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnExportar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        btnExportar.setText("Exportar BD");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        jButton1.setText("Importar BD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnExportar)
                .addGap(98, 98, 98)
                .addComponent(jButton1)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportar)
                    .addComponent(jButton1))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:

        JFileChooser bd = new JFileChooser();

        int dt = bd.showSaveDialog(null);

        if (dt == JFileChooser.APPROVE_OPTION) {

            String ubicacion = bd.getSelectedFile().getAbsolutePath();
            String ruta=ubicacion+".sql";
            
            try {
                Process p = Runtime.getRuntime().exec("http://192.168.0.231/phpmyadmin/index.php?token=ec7ab6726dfe1b9e7a0554910e0216cd#PMAURL-12:db_structure.php?db=dbalmacen&table=&server=1&target=&token=ec7ab6726dfe1b9e7a0554910e0216cd"+"-u "+ user + "-p"+pass+" --routines -B"+db);
                InputStream is= p.getInputStream();
                FileOutputStream fo=new FileOutputStream(ruta);
                
                byte[] buffer =new byte[1000];
                int leido=is.read();
                while(leido>0){
                    fo.write(buffer, 0, leido);
                    leido=is.read();
                }
                fo.close();
                
                JOptionPane.showMessageDialog(rootPane, "BD Exportada exitosamente");
            } catch (Exception e) {
                Logger.getLogger(frmRespaldarRestaura.class.getName()).log(Level.SEVERE,null,e);
            }
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          JFileChooser bd = new JFileChooser();

        int dt = bd.showSaveDialog(null);

        if (dt == JFileChooser.APPROVE_OPTION) {
              String ubicacion = bd.getSelectedFile().getAbsolutePath();
              String ruta=ubicacion+".sql";
            try {
                Process p = Runtime.getRuntime().exec(ruta+"-u "+ user + "-p"+pass+" --routines -B"+db);
                OutputStream is= p.getOutputStream();
                FileInputStream fo=new FileInputStream(ruta);
                
                byte[] buffer =new byte[1000];
                int leido=fo.read();
                while(leido>0){
                    is.write(buffer, 0, leido);
                    leido=fo.read();
                }
                fo.close();
            } catch (Exception e) {
                Logger.getLogger(frmRespaldarRestaura.class.getName()).log(Level.SEVERE,null,e);
            }
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
